version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
workflows:
    eslint:
      jobs:
        - eslint
